repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.7.4'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
        exclude: ^docs/cookbooks/  # Ignore files under docs/cookbooks
      - id: ruff-format
        exclude: ^docs/cookbooks/  # Ignore files under docs/cookbooks

  - repo: local
    hooks:
    - id: check-license
      name: Check License
      entry: python licenses/update_license.py . licenses/license_template.txt 
      language: system
      types: [python]
